"""Initial migration

Revision ID: ae19117b1ba7
Revises: 
Create Date: 2025-10-25 01:35:52.413144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae19117b1ba7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auction_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.Text(), nullable=True),
    sa.Column('age', sa.Text(), nullable=True),
    sa.Column('sire', sa.String(length=100), nullable=True),
    sa.Column('dam', sa.String(length=100), nullable=True),
    sa.Column('dam_sire', sa.String(length=100), nullable=True),
    sa.Column('race_record', sa.Text(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('total_prize_start', sa.Float(), nullable=True),
    sa.Column('total_prize_latest', sa.Float(), nullable=True),
    sa.Column('sold_price', sa.Text(), nullable=True),
    sa.Column('auction_date', sa.Text(), nullable=True),
    sa.Column('seller', sa.Text(), nullable=True),
    sa.Column('disease_tags', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('primary_image', sa.String(length=500), nullable=True),
    sa.Column('jbis_url', sa.String(length=500), nullable=True),
    sa.Column('detail_url', sa.String(length=500), nullable=True),
    sa.Column('unsold_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horses_auction_id'), 'horses', ['auction_id'], unique=True)
    op.create_table('auction_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('auction_date', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('seller', sa.String(length=100), nullable=True),
    sa.Column('buyer', sa.String(length=100), nullable=True),
    sa.Column('auction_house', sa.String(length=100), nullable=True),
    sa.Column('auction_name', sa.String(length=200), nullable=True),
    sa.Column('lot_number', sa.String(length=20), nullable=True),
    sa.Column('auction_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auction_histories')
    op.drop_index(op.f('ix_horses_auction_id'), table_name='horses')
    op.drop_table('horses')
    # ### end Alembic commands ###
