"""add_prize_money_to_horses

Revision ID: 1daa8369af8b
Revises: 63965333a44e
Create Date: 2025-11-03 01:50:14.950034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1daa8369af8b'
down_revision: Union[str, Sequence[str], None] = '63965333a44e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_auction_histories_user_id_users'), 'auction_histories', type_='foreignkey')
    op.drop_constraint(op.f('fk_auction_histories_horse_id_horses'), 'auction_histories', type_='foreignkey')
    op.create_foreign_key('fk_auction_histories_user_id_users', 'auction_histories', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('fk_auction_histories_horse_id_horses', 'auction_histories', 'horses', ['horse_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('horses', sa.Column('prize_money', sa.Float(), nullable=True))
    op.drop_constraint(op.f('fk_horses_owner_id_users'), 'horses', type_='foreignkey')
    op.drop_constraint(op.f('fk_horses_latest_auction_id_auction_histories'), 'horses', type_='foreignkey')
    op.create_foreign_key('fk_horses_owner_id_users', 'horses', 'users', ['owner_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('fk_horses_latest_auction_id_auction_histories', 'horses', 'auction_histories', ['latest_auction_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_horses_latest_auction_id_auction_histories', 'horses', schema='public', type_='foreignkey')
    op.drop_constraint('fk_horses_owner_id_users', 'horses', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_horses_latest_auction_id_auction_histories'), 'horses', 'auction_histories', ['latest_auction_id'], ['id'])
    op.create_foreign_key(op.f('fk_horses_owner_id_users'), 'horses', 'users', ['owner_id'], ['id'])
    op.drop_column('horses', 'prize_money')
    op.drop_constraint('fk_auction_histories_horse_id_horses', 'auction_histories', schema='public', type_='foreignkey')
    op.drop_constraint('fk_auction_histories_user_id_users', 'auction_histories', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_auction_histories_horse_id_horses'), 'auction_histories', 'horses', ['horse_id'], ['id'])
    op.create_foreign_key(op.f('fk_auction_histories_user_id_users'), 'auction_histories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
