"""add_missing_columns

Revision ID: 24058f3025d8
Revises: ec48a8ef028e
Create Date: 2025-09-15 01:15:35.010333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24058f3025d8'
down_revision: Union[str, Sequence[str], None] = 'ec48a8ef028e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horses', sa.Column('jbis_url', sa.String(length=500), nullable=True))
    op.add_column('horses', sa.Column('auction_url', sa.String(length=500), nullable=True))
    op.add_column('horses', sa.Column('is_unsold', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horses', 'is_unsold')
    op.drop_column('horses', 'auction_url')
    op.drop_column('horses', 'jbis_url')
    # ### end Alembic commands ###
