"""Remove owner_id, owner relationship and primary_image column

Revision ID: 2c9d01287823
Revises: 780646f748fd
Create Date: 2025-11-06 01:19:00.732775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c9d01287823'
down_revision: Union[str, Sequence[str], None] = '780646f748fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horses_backup_20251105')
    op.drop_constraint(op.f('fk_auction_histories_horse_id_horses'), 'auction_histories', type_='foreignkey')
    op.drop_constraint(op.f('fk_auction_histories_user_id_users'), 'auction_histories', type_='foreignkey')
    op.create_foreign_key('fk_auction_histories_horse_id_horses', 'auction_histories', 'horses', ['horse_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('fk_auction_histories_user_id_users', 'auction_histories', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    # まず、既存のデータを適切なJSON形式に変換
    op.execute("""
    UPDATE horses 
    SET unified_race_records = CASE 
        WHEN unified_race_records = true THEN '{}'::jsonb
        ELSE '[]'::jsonb
    END
    """)
    
    # 次に、カラムの型を変更
    op.alter_column('horses', 'unified_race_records',
               type_=postgresql.JSON(astext_type=sa.Text()),
               comment='統合されたレース記録（JSON形式）',
               postgresql_using='unified_race_records::jsonb',
               existing_type=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('fk_horses_owner_id_users'), 'horses', type_='foreignkey')
    op.drop_constraint(op.f('fk_horses_latest_auction_id_auction_histories'), 'horses', type_='foreignkey')
    op.create_foreign_key('fk_horses_latest_auction_id_auction_histories', 'horses', 'auction_histories', ['latest_auction_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_column('horses', 'primary_image')
    op.drop_column('horses', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horses', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('horses', sa.Column('primary_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint('fk_horses_latest_auction_id_auction_histories', 'horses', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_horses_latest_auction_id_auction_histories'), 'horses', 'auction_histories', ['latest_auction_id'], ['id'])
    op.create_foreign_key(op.f('fk_horses_owner_id_users'), 'horses', 'users', ['owner_id'], ['id'])
    op.alter_column('horses', 'unified_race_records',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.BOOLEAN(),
               comment=None,
               existing_comment='統合されたレース記録（JSON形式）',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint('fk_auction_histories_user_id_users', 'auction_histories', schema='public', type_='foreignkey')
    op.drop_constraint('fk_auction_histories_horse_id_horses', 'auction_histories', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_auction_histories_user_id_users'), 'auction_histories', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_auction_histories_horse_id_horses'), 'auction_histories', 'horses', ['horse_id'], ['id'])
    op.create_table('horses_backup_20251105',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('auction_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sex', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('age', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sire', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('dam', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('dam_sire', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('race_record', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_prize_start', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_prize_latest', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sold_price', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('auction_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seller', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('disease_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('primary_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('jbis_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('detail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('unsold_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latest_auction_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_unsold', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bid_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prize_money', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unified_race_records', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
