"""Add race_records field to Horse model

Revision ID: 2e090c6f3495
Revises: 
Create Date: 2025-11-14 12:57:34.639578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e090c6f3495'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horses_backup_20251105')
    op.drop_index(op.f('ix_horse_prize_history_horse_id'), table_name='horse_prize_history')
    op.drop_index(op.f('ix_horse_prize_history_recorded_at'), table_name='horse_prize_history')
    op.drop_table('horse_prize_history')
    op.drop_constraint(op.f('fk_auction_histories_user_id_users'), 'auction_histories', type_='foreignkey')
    op.drop_constraint(op.f('fk_auction_histories_horse_id_horses'), 'auction_histories', type_='foreignkey')
    op.create_foreign_key('fk_auction_histories_user_id_users', 'auction_histories', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('fk_auction_histories_horse_id_horses', 'auction_histories', 'horses', ['horse_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_column('auction_histories', 'comment')
    op.drop_constraint(op.f('fk_horses_latest_auction_id_auction_histories'), 'horses', type_='foreignkey')
    op.create_foreign_key('fk_horses_latest_auction_id_auction_histories', 'horses', 'auction_histories', ['latest_auction_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_column('horses', 'is_retired')
    op.drop_column('horses', 'last_prize_update')
    op.drop_column('horses', 'next_update_due_date')
    op.drop_column('horses', 'update_interval_months')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horses', sa.Column('update_interval_months', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False))
    op.add_column('horses', sa.Column('next_update_due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('horses', sa.Column('last_prize_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('horses', sa.Column('is_retired', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint('fk_horses_latest_auction_id_auction_histories', 'horses', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_horses_latest_auction_id_auction_histories'), 'horses', 'auction_histories', ['latest_auction_id'], ['id'])
    op.add_column('auction_histories', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_auction_histories_horse_id_horses', 'auction_histories', schema='public', type_='foreignkey')
    op.drop_constraint('fk_auction_histories_user_id_users', 'auction_histories', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_auction_histories_horse_id_horses'), 'auction_histories', 'horses', ['horse_id'], ['id'])
    op.create_foreign_key(op.f('fk_auction_histories_user_id_users'), 'auction_histories', 'users', ['user_id'], ['id'])
    op.create_table('horse_prize_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('horse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], name=op.f('horse_prize_history_horse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('horse_prize_history_pkey'))
    )
    op.create_index(op.f('ix_horse_prize_history_recorded_at'), 'horse_prize_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_horse_prize_history_horse_id'), 'horse_prize_history', ['horse_id'], unique=False)
    op.create_table('horses_backup_20251105',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('auction_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sex', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('age', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sire', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('dam', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('dam_sire', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('race_record', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_prize_start', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_prize_latest', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sold_price', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('auction_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seller', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('disease_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('primary_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('jbis_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('detail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('unsold_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latest_auction_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_unsold', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bid_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prize_money', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unified_race_records', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
