"""Add scraped_at column to horses table

Revision ID: 45d331e503e2
Revises: cb0c579f62b4
Create Date: 2025-11-03 01:24:02.315017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d331e503e2'
down_revision: Union[str, Sequence[str], None] = 'cb0c579f62b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction_histories', sa.Column('scraped_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('auction_histories_user_id_fkey'), 'auction_histories', type_='foreignkey')
    op.drop_constraint(op.f('auction_histories_horse_id_fkey'), 'auction_histories', type_='foreignkey')
    op.create_foreign_key('fk_auction_histories_horse_id_horses', 'auction_histories', 'horses', ['horse_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('fk_auction_histories_user_id_users', 'auction_histories', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('horses', sa.Column('scraped_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_horses_auction_id'), table_name='horses')
    op.create_index(op.f('ix_public_horses_auction_id'), 'horses', ['auction_id'], unique=True, schema='public')
    op.drop_constraint(op.f('horses_latest_auction_id_fkey'), 'horses', type_='foreignkey')
    op.drop_constraint(op.f('horses_owner_id_fkey'), 'horses', type_='foreignkey')
    op.create_foreign_key('fk_horses_latest_auction_id_auction_histories', 'horses', 'auction_histories', ['latest_auction_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('fk_horses_owner_id_users', 'horses', 'users', ['owner_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_column('horses', 'is_unsold')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_public_users_email'), 'users', ['email'], unique=True, schema='public')
    op.create_index(op.f('ix_public_users_id'), 'users', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_users_username'), 'users', ['username'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_users_username'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_id'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_email'), table_name='users', schema='public')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('horses', sa.Column('is_unsold', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint('fk_horses_owner_id_users', 'horses', schema='public', type_='foreignkey')
    op.drop_constraint('fk_horses_latest_auction_id_auction_histories', 'horses', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('horses_owner_id_fkey'), 'horses', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('horses_latest_auction_id_fkey'), 'horses', 'auction_histories', ['latest_auction_id'], ['id'])
    op.drop_index(op.f('ix_public_horses_auction_id'), table_name='horses', schema='public')
    op.create_index(op.f('ix_horses_auction_id'), 'horses', ['auction_id'], unique=True)
    op.drop_column('horses', 'scraped_at')
    op.drop_constraint('fk_auction_histories_user_id_users', 'auction_histories', schema='public', type_='foreignkey')
    op.drop_constraint('fk_auction_histories_horse_id_horses', 'auction_histories', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('auction_histories_horse_id_fkey'), 'auction_histories', 'horses', ['horse_id'], ['id'])
    op.create_foreign_key(op.f('auction_histories_user_id_fkey'), 'auction_histories', 'users', ['user_id'], ['id'])
    op.drop_column('auction_histories', 'scraped_at')
    # ### end Alembic commands ###
