"""add_race_records_column_to_horses

Revision ID: 4ce4de32b4c3
Revises: 1daa8369af8b
Create Date: 2025-11-03 02:09:10.495353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce4de32b4c3'
down_revision: Union[str, Sequence[str], None] = '1daa8369af8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horses', sa.Column('race_records', sa.Text(), nullable=True), schema='public')
    op.drop_constraint(op.f('fk_auction_histories_user_id_users'), 'auction_histories', type_='foreignkey')
    op.drop_constraint(op.f('fk_auction_histories_horse_id_horses'), 'auction_histories', type_='foreignkey')
    op.create_foreign_key('fk_auction_histories_user_id_users', 'auction_histories', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('fk_auction_histories_horse_id_horses', 'auction_histories', 'horses', ['horse_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('fk_horses_latest_auction_id_auction_histories'), 'horses', type_='foreignkey')
    op.drop_constraint(op.f('fk_horses_owner_id_users'), 'horses', type_='foreignkey')
    op.create_foreign_key('fk_horses_latest_auction_id_auction_histories', 'horses', 'auction_histories', ['latest_auction_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('fk_horses_owner_id_users', 'horses', 'users', ['owner_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horses', 'race_records', schema='public')
    op.drop_constraint('fk_horses_owner_id_users', 'horses', schema='public', type_='foreignkey')
    op.drop_constraint('fk_horses_latest_auction_id_auction_histories', 'horses', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_horses_owner_id_users'), 'horses', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('fk_horses_latest_auction_id_auction_histories'), 'horses', 'auction_histories', ['latest_auction_id'], ['id'])
    op.drop_constraint('fk_auction_histories_horse_id_horses', 'auction_histories', schema='public', type_='foreignkey')
    op.drop_constraint('fk_auction_histories_user_id_users', 'auction_histories', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_auction_histories_horse_id_horses'), 'auction_histories', 'horses', ['horse_id'], ['id'])
    op.create_foreign_key(op.f('fk_auction_histories_user_id_users'), 'auction_histories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
