"""Add is_unsold and bid_count to horses table

Revision ID: 5d8eb30c4cf5
Revises: 20251026_add_latest_auction_id
Create Date: 2025-10-28 13:17:36.820908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8eb30c4cf5'
down_revision: Union[str, Sequence[str], None] = '20251026_add_latest_auction_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horses', sa.Column('is_unsold', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('horses', sa.Column('bid_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horses', 'bid_count')
    op.drop_column('horses', 'is_unsold')
    # ### end Alembic commands ###
