"""Add damsire column to horses table

Revision ID: 63965333a44e
Revises: 2c2cb9aa6c58
Create Date: 2025-11-03 01:42:16.017064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63965333a44e'
down_revision: Union[str, Sequence[str], None] = '2c2cb9aa6c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_auction_histories_horse_id_horses'), 'auction_histories', type_='foreignkey')
    op.drop_constraint(op.f('fk_auction_histories_user_id_users'), 'auction_histories', type_='foreignkey')
    op.create_foreign_key('fk_auction_histories_user_id_users', 'auction_histories', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('fk_auction_histories_horse_id_horses', 'auction_histories', 'horses', ['horse_id'], ['id'], source_schema='public', referent_schema='public')
    # damsireカラムを追加
    op.add_column('horses', sa.Column('damsire', sa.String(length=100), nullable=True))
    
    # damsireカラムをdam_sireの値で初期化
    op.execute("""
        UPDATE horses 
        SET damsire = dam_sire
        WHERE dam_sire IS NOT NULL
    """)
    
    op.drop_constraint(op.f('fk_horses_latest_auction_id_auction_histories'), 'horses', type_='foreignkey')
    op.drop_constraint(op.f('fk_horses_owner_id_users'), 'horses', type_='foreignkey')
    op.create_foreign_key('fk_horses_owner_id_users', 'horses', 'users', ['owner_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('fk_horses_latest_auction_id_auction_histories', 'horses', 'auction_histories', ['latest_auction_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_horses_latest_auction_id_auction_histories', 'horses', schema='public', type_='foreignkey')
    op.drop_constraint('fk_horses_owner_id_users', 'horses', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_horses_owner_id_users'), 'horses', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('fk_horses_latest_auction_id_auction_histories'), 'horses', 'auction_histories', ['latest_auction_id'], ['id'])
    # damsireカラムを削除
    op.drop_column('horses', 'damsire')
    op.drop_constraint('fk_auction_histories_horse_id_horses', 'auction_histories', schema='public', type_='foreignkey')
    op.drop_constraint('fk_auction_histories_user_id_users', 'auction_histories', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_auction_histories_user_id_users'), 'auction_histories', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_auction_histories_horse_id_horses'), 'auction_histories', 'horses', ['horse_id'], ['id'])
    # ### end Alembic commands ###
