"""Change is_unsold to column and add scraped_at to auction_histories

Revision ID: acd15663a3bc
Revises: 45d331e503e2
Create Date: 2025-11-03 01:30:15.302566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd15663a3bc'
down_revision: Union[str, Sequence[str], None] = '45d331e503e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 既存の外部キー制約を削除
    op.drop_constraint(op.f('fk_auction_histories_horse_id_horses'), 'auction_histories', type_='foreignkey')
    op.drop_constraint(op.f('fk_auction_histories_user_id_users'), 'auction_histories', type_='foreignkey')
    
    # 新しい外部キー制約を追加（スキーマを明示的に指定）
    op.create_foreign_key('fk_auction_histories_horse_id_horses', 'auction_histories', 'horses', ['horse_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('fk_auction_histories_user_id_users', 'auction_histories', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    
    # NULL許容でカラムを追加
    op.add_column('horses', sa.Column('is_unsold', sa.Boolean(), nullable=True, comment='最新のオークション情報から自動設定される主取りフラグ'))
    
    # 既存のレコードにデフォルト値を設定
    op.execute("UPDATE horses SET is_unsold = false WHERE is_unsold IS NULL")
    
    # NOT NULL制約を追加
    op.alter_column('horses', 'is_unsold', nullable=False)
    
    # 既存の外部キー制約を削除して再作成（スキーマを明示的に指定）
    op.drop_constraint(op.f('fk_horses_latest_auction_id_auction_histories'), 'horses', type_='foreignkey')
    op.drop_constraint(op.f('fk_horses_owner_id_users'), 'horses', type_='foreignkey')
    op.create_foreign_key('fk_horses_owner_id_users', 'horses', 'users', ['owner_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('fk_horses_latest_auction_id_auction_histories', 'horses', 'auction_histories', ['latest_auction_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_horses_latest_auction_id_auction_histories', 'horses', schema='public', type_='foreignkey')
    op.drop_constraint('fk_horses_owner_id_users', 'horses', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_horses_owner_id_users'), 'horses', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('fk_horses_latest_auction_id_auction_histories'), 'horses', 'auction_histories', ['latest_auction_id'], ['id'])
    op.drop_column('horses', 'is_unsold')
    op.drop_constraint('fk_auction_histories_user_id_users', 'auction_histories', schema='public', type_='foreignkey')
    op.drop_constraint('fk_auction_histories_horse_id_horses', 'auction_histories', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_auction_histories_user_id_users'), 'auction_histories', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_auction_histories_horse_id_horses'), 'auction_histories', 'horses', ['horse_id'], ['id'])
    op.alter_column('auction_histories', 'is_unsold',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='主取りフラグ',
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
