name: Combined Scraping Workflow

on:
  schedule:
    - cron: '59 14 * * 4,0'  # 毎週木曜・日曜 23:59 JST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape-auction:
    name: Scrape Auction Data
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run accumulative scraper
        run: python scripts/accumulative_scraper.py
        
      - name: Commit and push auction data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add static-frontend/public/data/horses_history.json
          git commit -m "Update horse history data" || echo "No changes to commit"
          git push
          
  update-data:
    name: Update Additional Data
    needs: scrape-auction  # scrape-auction ジョブの完了を待つ
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install beautifulsoup4 lxml tqdm
          
      - name: Add execute permissions
        run: |
          chmod +x scripts/run_updates.py
          chmod +x scripts/improved_scraper.py
          chmod +x scripts/update_jbis_history_data.py
          
      - name: Run data updates
        run: |
          cd scripts
          python run_updates.py
          
      - name: Commit and push all data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add static-frontend/public/data/*.json
          git commit -m "Update all horse data" || echo "No changes to commit"
          git push
