# このワークフローは楽天サラブレッドオークションのデータを定期的にスクレイピングし、
# static-frontend/public/data/horses.json を自動更新します。
# スクレイピングスクリプトのパスや出力先を変更した場合は、必ずこのYAMLも修正してください。
name: Scrape Auction Horses

on:
  schedule:
    - cron: '59 14 * * 4,0'  # 毎週木曜・日曜 23:59 JST（UTC 14:59）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run accumulative auction scraper
        run: python scripts/accumulative_scraper.py
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add static-frontend/public/data/horses_history.json
          git commit -m "Update horse data (auto scrape) - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push 