name: Scrape JBIS Growth Rate

on:
  schedule:
    - cron: '0 3 1 * *'  # 毎月1日 3:00
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update JBIS history data
        run: python scripts/update_jbis_history_data.py
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add static-frontend/public/data/horses.json
          git commit -m "Update growth rate (auto scrape) - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push 