name: Scrape Horse Data

on:
  schedule:
    - cron: "0 12 * * 2,6"  # 火・土 21:00 JST (UTC+9)
  workflow_dispatch:       # 手動実行も可能
  push:
    branches: [ main ]
    paths:
      - 'scripts/**'
      - 'requirements.txt'

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run scraper
        run: python scripts/scrape.py

      - name: Commit & Push scraped data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/horses.json
          git commit -m "Update horse data (auto scrape) - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push

      - name: Create deployment status
        if: always()
        run: |
          echo "Scraping completed at $(date)"
          echo "Check data/horses.json for updated data" 